language: node_js
sudo: false
node_js:
  - "10"
cache:
  directories:
    - node_modules
before_install:
  - npm install
script:
  - npm run test:coverage
  - npm run build
after_script:
  - npm run coverage
